### ISSUE TITLE
Some problems w/ ParseServerCreatureMove

### ISSUE THREAD

**Issue by vinioliveirasilva** [jo3bingham/sharpmaptracker#1]
while i working on some bugs, could not figure out how to solve this.

```
[ParseServerCreatureMove] Old tile not found.
Last Packets: 6D 
Packet Bytes: 6D E7 80 96 7E 08 05 E7 80 97 7E 08 
```

**Comment by jo3bingham** [comment]
Honestly, I don't have the time to track down the issue here. Note that this isn't my code, I've just been keeping the protocol/addresses updated to work with the latest client. If you fix it, I'll be more than happy to merge it with mine, though. I plan on writing my own tracker in the future that will be more reliable than this one, but I can't say when I'll be able to get around to it.

However, thanks for the issue. Hopefully, you, or someone else, can fix these issues since I do not have the time to.

**Comment by vinioliveirasilva** [comment]
I will try, when starting your MapTracker let me know.
